
services:

  techefx-eureka-namng-service:
    image: techefx-eureka-naming-server
    ports:
      - "8761:8761"
    networks:
      - test-network


  techefx-product-stock-service:
    image: techefx-product-stock-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-namng-service:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
    ports:
      - "8800:8800"
    #    links:
    #      - zipkin
    depends_on:
      - techefx-eureka-namng-service
    #      - zipkin
    networks:
      - test-network


  techefx-product-enquiry-service:
    image: techefx-product-enquiry-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-namng-service:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
    ports:
      - "8700:8700"
    #   links:
    #     - zipkin
    depends_on:
      - techefx-product-stock-service
    #     - zipkin
    networks:
      - test-network


  techefx-spring-cloud-api-gateway-service:
    image: techefx-spring-cloud-api-gateway-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-namng-service:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
 #       -DENQUIRY_SERVICE=http://techefx-product-enquiry-service:9700/
    ports:
      - "8900:8900"
    #   links:
    #     - zipkin
    depends_on:
      - techefx-eureka-namng-service
      - techefx-product-enquiry-service
      - techefx-product-stock-service
    #      - zipkin
    networks:
      - test-network


  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    depends_on:
      - techefx-eureka-namng-service
    networks:
      - test-network



networks:
  test-network:

